import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/layout/Footer.js'


const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>    
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="APUlogo.png" />        
      </Head>
      <main className={styles.header}>             
        <a href="http://localhost:3000/HomePM">
            <table>
                <tbody>
                    <tr>
                        <td>
                            <Image
                            src="/APUlogo.png"
                            alt="APU Logo"
                            className={styles.vercelLogo}
                            width={50}
                            height={50}
                            priority            
                            />
                        
                        </td>
                        <td><b className={styles.title1}>ApFYPCentre</b></td>                     
                        <td><a href="http://localhost:3000/ProfilePM" className={styles.button1}>Profile</a></td>
                        <td><a href="" className={styles.button4}>Student</a></td>
                        <td><a href="" className={styles.button2}>Staff</a></td>
                        <td><a href="" className={styles.button2}>Submission</a></td>
                        <td> <br/></td>
                        <td><br/></td>
                        <td><a href="http://localhost:3000/" className={styles.box3}><u>Logout</u></a></td>
                    </tr>
                </tbody>                
            </table>
        </a>                                                  
      </main>       
      <div className={styles.content3}>
        <a href="http://localhost:3000/HomePM">
        <div className={styles.button5}>
          Back 
        </div>
        </a>
      </div>                               
      <div className={styles.contentbox2}>
        <form action="">
          <select name="field">
            <option value="-">All</option>
            <option value="IT">IT</option>
            <option value="BUS">Business</option>
            <option value="ENG">Engineering</option>
          </select>
          <select name="Specialize">
            <option value="-">-</option>
          </select>
        </form>
      </div>
             
      <br /><br /><br />
      <Footer />
      </>
  )
}