import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/layout/Header.js'
import Footer from '@/layout/Footer.js'
import {useState} from 'react'
import axios from 'axios';


const inter = Inter({ subsets: ['latin'] })

export default function Login() {
  const[email, setEmail] = useState('');
  const[password, setPassword] = useState('');
  const submitForm = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
  
    try {
      const response = await axios.post('http://localhost:8000/api/login', {
        email,
        password,
      });
  
      if (response.status === 200) {
        const data = response.data;
        console.log(data);
      } else {
        console.error('Login request failed');
      }
    } catch (error) {
      console.error('An error occurred during the login request:', error);
    }
  };
  
  
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="APUlogo.png" />        
      </Head>
      <Header />
      <div className={styles.main}>
        <div className={styles.center}>
          <h1 className={styles.word4}>Login</h1>
        </div>
        <div className={styles.box1}>
            <div className={styles.box2}>
              <form onSubmit={submitForm} className={styles.word3}>
                Email <br />
                <input type="text" required  value ={email} onChange={(event)=>setEmail(event.target.value)}name="email"/><br /><br />
                Password <br />
                <input type="password"required value={password} onChange={(event)=>setPassword(event.target.value)} name="password"/><br /><br />
                <button type="submit" value="login" name="login" className={styles.box2button}>LOGIN</button>
              </form>
            </div>
        </div>
      </div><br /><br /><br />
      <Footer />
      </>
  )
}