import Head from 'next/head'
import {Roboto} from 'next/font/google'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/layout/Header.js'
import Footer from '@/layout/Footer.js'


const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ weight:'300',subsets:['latin']})
export default function Home() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="APUlogo.png" />        
      </Head>
      <Header />
      <div className={styles.main}>
        <div className={styles.center}>
          <h1>Login</h1>
        </div>
        <div className={styles.box1}>
            <div className={styles.box2}>
              <form action="" className={roboto.className}>
                TP Number: <br />
                <input type="text" required name="tp"/><br /><br />
                Password: <br />
                <input type="password"required name="password"/><br /><br />
                <a href="http://localhost:3000/HomeSupervisor"><button type="submit" value="login" name="login" className={styles.box2button}>LOGIN</button></a>
              </form>
            </div>
        </div>
      </div><br /><br /><br />
      <Footer />
      </>
  )
}

