import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/layout/Footer.js'
import Table from '@/layout/TableStu3.js'
import { getPMLecturerProfile } from './api/api'
import{logout} from '@/pages/api/api'
import { useEffect, useState } from 'react'

interface Lecturer{
id:string;
name: string;
email: string;
field_of_study:string;
}


const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  const [lecturer, setData] = useState([]);
    
    useEffect(() => {
        const fetchData = async () => {
            try {
                const token = localStorage.getItem('id');
                console.log(token);                
                const lecturer = await getPMLecturerProfile(token);                                
                console.log(lecturer);
                setData(lecturer);
            } catch (error) {
                console.log('Error fetching data: ', error);
            }
        };
        fetchData();
    }, []);
    const handleLogout = async()=>{
      try{
        await logout();
      }catch(error){
        console.error('Error.logging out: ', error);
      }
    };
  return (
    <>    
      <Head>
        <title>Lecturer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="APUlogo.png" />        
      </Head>
      <main className={styles.header}>                     
            <table>
                <tbody>
                    <tr>
                        <td><a href="http://localhost:3000/HomePM">
                            <Image
                            src="/APUlogo.png"
                            alt="APU Logo"
                            className={styles.vercelLogo}
                            width={50}
                            height={50}
                            priority            
                            />
                        </a>
                        </td>
                        <td><a href="http://localhost:3000/HomePM"><b className={styles.title4}>ApFYPCentre</b></a></td>                     
                        <td><a href="http://localhost:3000/ProfilePM" className={styles.button1}>Profile</a></td>
                        <td><a href="http://localhost:3000/StudentPM" className={styles.button2}>Student</a></td>
                        <td><a href="http://localhost:3000/StaffPM" className={styles.button4}>Lecturer</a></td>
                        <td><a href="http://localhost:3000/SubPM" className={styles.button2}>Mark</a></td>
                        <td> <br/></td>
                        <td><br/></td>
                        <td><a href="http://localhost:3000" className={styles.box3} onClick={handleLogout}><u>Logout</u></a></td>
                    </tr>
                </tbody>                
            </table>                                                          
      </main>       
      <div className={styles.content5}>
        <a href="http://localhost:3000/StaffPM">
        <div className={styles.button5}>
          Back 
        </div>
        </a>
      </div>  
      
      <div className={styles.contentbox3}>
      {lecturer && (
      <>
      <div className={styles.box11a} key={lecturer.id}><h2>{lecturer.name}</h2><br /> {lecturer.id}<br/>{lecturer.field_of_study} <br />{lecturer.email}</div>
      </>
       ) }
         </div>                       
      <br /><br /><br />    <br /><br /><br />      <br/>                    
      <div className={styles.contentbox3}>
      <Table />      
      </div>                                
             
      <br /><br /><br />
      <Footer />
      </>
  )
}