import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/layout/Footer.js'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })
export default function Home() {
    return (
      <>    
        <Head>
          <title>Profile</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-wxidth, initial-scale=1" />
          <link rel="icon" href="APUlogo.png" />        
        </Head>
        <main className={styles.header}>                     
              <table>
                  <tbody>
                      <tr>
                          <td><a href="http://localhost:3000/HomePM">
                              <Image
                              src="/APUlogo.png"
                              alt="APU Logo"
                              className={styles.vercelLogo}
                              width={50}
                              height={50}
                              priority            
                              />
                          </a>
                          </td>
                          <td><a href="http://localhost:3000/HomePM"><b className={styles.title1}>ApFYPCentre</b></a></td>                     
                          <td><a href="http://localhost:3000/ProfilePM" className={styles.button3}>Profile</a></td>
                          <td><a href="http://localhost:3000/StudentPM" className={styles.button2}>Student</a></td>
                          <td><a href="http://localhost:3000/StaffPM" className={styles.button2}>Lecturer</a></td>
                          <td><a href="" className={styles.button2}>Submission</a></td>
                          <td> <br/></td>
                          <td><br/></td>
                          <td><a href="http://localhost:3000" className={styles.box3}><u>Logout</u></a></td>
                      </tr>
                  </tbody>                
              </table>
        </main>
        <div className={styles.content3}>
        <a href="http://localhost:3000/ProfilePM">
          <div className={styles.button5}>
            Back 
          </div>
        </a>  <br />    
      </div> 
      <div className={styles.contentbox4}>           
          <div className={styles.image} ></div>
          <form action=""> 
          <div className={styles.namebox1}>
          <input type="text" placeholder="Name"/><br /><br/>
          <input type="text" placeholder="Field"/>
          </div> 
          
          <div className={styles.infobox2}>
          
          Email  : <input type="email" name="" id="" /><br /><br />
          Tel    : <input type="text" /><br />        <br />       
          Preferable Platform : <input type="text" />   
          </div>
            <a href="http://localhost:3000/Profile"><button type="submit" className={styles.button6}>Done Editing</button></a>
          </form>  
          <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />                                                    
            <br /><br /><br /><br /><br /><br />
        </div>
            <Footer />
      </>
  )
}