import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/layout/Footer.js'

const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>    
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="APUlogo.png" />        
      </Head>
      <main className={styles.header}>             
        <a href="http://localhost:3000/HomePM">
            <table>
                <tbody>
                    <tr>
                        <td>
                            <Image
                            src="/APUlogo.png"
                            alt="APU Logo"
                            className={styles.vercelLogo}
                            width={50}
                            height={50}
                            priority            
                            />
                        
                        </td>
                        <td><b className={styles.title1}>ApFYPCentre</b></td>                     
                        <td><a href="http://localhost:3000/ProfilePM" className={styles.button3}>Profile</a></td>
                        <td><a href="http://localhost:3000/StudentPM" className={styles.button2}>Student</a></td>
                        <td><a href="" className={styles.button2}>Staff</a></td>
                        <td><a href="" className={styles.button2}>Submission</a></td>
                        <td> <br/></td>
                        <td><br/></td>
                        <td><a href="http://localhost:3000/" className={styles.box3}><u>Logout</u></a></td>
                    </tr>
                </tbody>                
            </table>
        </a>                                                  
      </main>       
      <div className={styles.content3}>
        <a href="http://localhost:3000/HomePM">
          <div className={styles.button5}>
            Back 
          </div>
        </a>  <br />    
      </div>        
        <div className={styles.contentbox1}>           
          <div className={styles.image}></div>
          <div className={styles.namebox}>
          Name <br />
          Lecture
          </div> 
          <div className={styles.infobox}>
          Email : <br />
          Tel : 0123456789             
          <form action="">     
          Preferable Platform :     
            <select name="platform">
              <option value="-">Select One</option>
              <option value="teams">MS Teams</option>
              <option value="whatsapp">WhatsApp</option>
            </select>
            <input type="submit" value="Confirm" className={styles.button6} />
                   
          </form>                                              
          </div>  
          
        </div>
        <div className={styles.contentbox}>
          Calendar
        </div>
        <div className={styles.line1}></div>         
      <br /><br /><br />
      <Footer />
      </>
  )
}
