import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/layout/Footer.js'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
      <>
        <Head>
          <title>Staff</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="APUlogo.png" />        
        </Head>
        <main className={styles.header}>                     
              <table>
                  <tbody>
                      <tr>
                          <td><a href="http://localhost:3000/HomeStu">
                              <Image
                              src="/APUlogo.png"
                              alt="APU Logo"
                              className={styles.vercelLogo}
                              width={50}
                              height={50}
                              priority            
                              />
                          </a>
                          </td>
                          <td><a href="http://localhost:3000/HomeStu"><b className={styles.title1}>ApFYPCentre</b></a></td>                     
                          <td><a href="http://localhost:3000/ProfileStu" className={styles.button2}>Profile</a></td>
                          <td><a href="http://localhost:3000/SubStu" className={styles.button2}>Submission</a></td>                        
                          <td><a href="http://localhost:3000/StaffStu" className={styles.button3}>Staff</a></td>
                          <td> <br/></td>
                          <td><br/></td>
                          <td><a href="http://localhost:3000/login" className={styles.box6}><u>Logout</u></a></td>
                      </tr>
                  </tbody>                
              </table>                                                              
        </main>

        <div className={styles.content5}>
        <a href="http://localhost:3000/HomeStu">
          <div className={styles.button5}>
            Back 
          </div>
          </a>  <br />
      </div>
      <div className={styles.contentbox2a}>
      <form action="">
          <input type="text" name="Search"/>
          <button type="submit"><Image
                            src="/search_icon.png"
                            alt="Search"
                            className={styles.vercelLogo}
                            width={20}
                            height={10}
                            priority            
                            /></button>
      </form>
      </div> <br /><br /><br /><br />
        <div className={styles.content6}>
          <div className={styles.box10}>
            <div className={styles.text}>Project Manager</div>
            <div className={styles.image1}></div><br /><br /><br /><br /><br /><br />
            <div className={styles.text}><b>Name</b></div>

            </div>
          <div className={styles.line3}></div>
          <div className={styles.box10}>
            <div className={styles.text1}>Supervisor</div>
            <div className={styles.image1}></div><br /><br /><br /><br /><br /><br />
            <div className={styles.text}><b>Name</b></div>
          </div>          
          <div className={styles.line3}></div>
          <div className={styles.box10}>
            <div className={styles.text}>Second Marker</div>
            <div className={styles.image1}></div><br /><br /><br /><br /><br /><br />
            <div className={styles.text}><b>Name</b></div>      
          </div>
          
        </div>
        <br /><br /><br />
        <Footer />
        </>
  )
}