import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/layout/Footer.js'
import{logout} from '@/pages/api/api'
import { useEffect, useState } from 'react'
import { getMoodleAPI } from '@/pages/api/api'
import { getStuResult } from '@/pages/api/api'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data, setData] = useState([]);
  const [data1, setData1] = useState([]); 
  useEffect(() => {
      
    fetchData();
    fetchData1();

}, []);
  const handleLogout = async()=>{
    try{
      await logout();
    }catch(error){
      console.error('Error.logging out: ', error);
    }
  };
  const fetchData = async () => {
    try {
          const token = localStorage.getItem('token'); //Retrieving token from local storage)
          const data = await getMoodleAPI(token);
          console.log(token);
          setData(data);         
  } catch (error) {
      console.log('Error fetching data: ', error);
  }
};
const fetchData1 = async () => {
  try {
    const token = localStorage.getItem('token'); //Retrieving token from local storage)      
    console.log(token);
    const students = await getStuResult(token);
    setData1(students);
    console.log(students);
  } catch (error) {
    console.log('Error fetching data: ', error);
  }
};
  return (
    <>
      <Head>
        <title>Submission</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="APUlogo.png" />        
      </Head>
      <main className={styles.header}>                     
            <table>
                <tbody>
                    <tr>
                        <td><a href="http://localhost:3000/HomeStu">
                            <Image
                            src="/APUlogo.png"
                            alt="APU Logo"
                            className={styles.vercelLogo}
                            width={50}
                            height={50}
                            priority            
                            />
                        </a>
                        </td>
                        <td><a href="http://localhost:3000/HomeStu"><b className={styles.title4}>ApFYPCentre</b></a></td>                     
                        <td><a href="http://localhost:3000/ProfileStu" className={styles.button2}>Profile</a></td>
                        <td><a href="http://localhost:3000/SubStu" className={styles.button3}>Submission</a></td>                        
                        <td><a href="http://localhost:3000/StaffStu" className={styles.button2}>Lecturer</a></td>
                        <td> <br/></td>
                        <td><br/></td>
                        <td><a href="http://localhost:3000" className={styles.box6} onClick={handleLogout}><u>Logout</u></a></td>
                    </tr>
                </tbody>                
            </table>                                                              
      </main>
      
      <div className={styles.subhead}>
        <p>Field will be ticked by the Lecturer after received the submission. Please contact your Lecturer if there is any error occurs. Total Mark will be generated within 3-4 weeks after all the submission is completed.</p>
      </div>
      
      <div className={styles.content3}>
        <a href="http://localhost:3000/HomeStu">
          <div className={styles.button5}>
            Back 
          </div>
          </a>  
      </div>
    <br />
      <div className ={styles.subtitle}>
        <h1><b><u>Submission</u></b></h1>
      </div>

      <div className={styles.table}>
        <table>
          <tbody>
          <tr>
            <td>
              <input type="checkbox"  className={styles.checkbox1} name= "proposal" value="1" checked={data?.Pro !== null}   disabled/>              
            </td>
            <td>
            <div className={styles.subtext}>Proposal</div>
            </td>
          </tr>
          <tr>
            <td>
            <input type="checkbox"  className={styles.checkbox1} name= "IR" value="1" checked={data?.IR !== null}   disabled/>
            </td>
            <td>
              <div className={styles.subtext}>Information_Report(IR)</div>
            </td>
          </tr>
          <tr>
            <td>
            <input type="checkbox"  className={styles.checkbox1} name= "Documentation" value="1" checked={data?.Doc !== null}   disabled/>
            </td>
            <td>
              <div className={styles.subtext}>Documentation</div>
            </td>
          </tr>
          <tr>
            <td>
            <input type="checkbox"  className={styles.checkbox1} name= "Presentation" value="1" checked={data?.Pre !== null}   disabled/>
            </td>
            <td>
              <div className={styles.subtext}>Presentation</div>
            </td>
          </tr>
          <tr>
            <td>
              {data1 &&(<><div className={styles.subtext}>Total_Mark: <br/><h1><u>{data1.finalMark || data1.finalmark}</u></h1></div></>)}
            </td>                       
          </tr>
          </tbody>
        </table>
        <br />
        <label className={styles.word2}><a href=""><u>Log Sheet</u></a></label>
        <Image 
        src="/design-books1.png"
        alt="profile"
        className={styles.image6}
        width={100}
        height={100}               
        priority
      />
      </div>
      <br /><br /><br />
      <Footer />
      </>
  )
}