import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/layout/Footer.js'
import Table from '@/layout/TableSub.js'

const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>    
      <Head>
        <title>Submission</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-wxidth, initial-scale=1" />
        <link rel="icon" href="APUlogo.png" />        
      </Head>
      <main className={styles.header}>                     
            <table>
                <tbody>
                    <tr>
                        <td><a href="http://localhost:3000/HomeSup">
                            <Image
                            src="/APUlogo.png"
                            alt="APU Logo"
                            className={styles.vercelLogo}
                            width={50}
                            height={50}
                            priority            
                            />
                        </a>
                        </td>
                        <td><a href="http://localhost:3000/HomeSupervisor"><b className={styles.title1}>ApFYPCentre</b></a></td>                     
                        <td><a href="http://localhost:3000/ProfileSup" className={styles.button1}>Profile</a></td>
                        <td><a href="http://localhost:3000/StuSup" className={styles.button2}>Student</a></td>                        
                        <td><a href="http://localhost:3000/SubSup" className={styles.button4}>Submission</a></td>
                        <td> <br/></td>
                        <td><br/></td>
                        <td><a href="http://localhost:3000/login" className={styles.box3}><u>Logout</u></a></td>
                    </tr>
                </tbody>                
            </table>                                                         
      </main> 
        <div className={styles.content5}>
        <a href="http://localhost:3000/HomeSupervisor">
          <div className={styles.button5}>
            Back 
          </div>
          </a>  <br />
      </div>

      
      <br /><br /><br />                             
      
      <Table />  
        
        <br /><br /><br />
        <Footer />
        </>
  )
}